export default {
  ADD_NOTE: 'ADD_NOTE',
  ADD_NOTE_SUCCESS: 'ADD_NOTE_SUCCESS',
  ADD_NOTE_FAIL: 'ADD_NOTE_FAIL',

  FETCH_NOTE: 'FETCH_NOTE',
  FETCH_NOTE_SUCCESS: 'FETCH_NOTE_SUCCESS',
  FETCH_NOTE_FAIL: 'FETCH_NOTE_FAIL',

  UPDATE_NOTE: 'UPDATE_NOTE',
  UPDATE_NOTE_SUCCESS: 'UPDATE_NOTE_SUCCESS',
  UPDATE_NOTE_FAIL: 'UPDATE_NOTE_FAIL',

  REMOVE_NOTE: 'REMOVE_NOTE',
  REMOVE_NOTE_SUCCESS: 'REMOVE_NOTE_SUCCESS',
  REMOVE_NOTE_FAIL: 'REMOVE_NOTE_FAIL',

  FETCH_NOTE_LIST: 'FETCH_NOTE_LIST',
  FETCH_NOTE_LIST_SUCCESS: 'FETCH_NOTE_LIST_SUCCESS',
  FETCH_NOTE_LIST_FAIL: 'FETCH_NOTE_LIST_FAIL',
}
