export default {
  ADD_NOTEPAD: 'ADD_NOTEPAD',
  ADD_NOTEPAD_SUCCESS: 'ADD_NOTEPAD_SUCCESS',
  ADD_NOTEPAD_FAIL: 'ADD_NOTEPAD_FAIL',

  FETCH_NOTEPAD: 'FETCH_NOTEPAD',
  FETCH_NOTEPAD_SUCCESS: 'FETCH_NOTEPAD_SUCCESS',
  FETCH_NOTEPAD_FAIL: 'FETCH_NOTEPAD_FAIL',

  UPDATE_NOTEPAD: 'UPDATE_NOTEPAD',
  UPDATE_NOTEPAD_SUCCESS: 'UPDATE_NOTEPAD_SUCCESS',
  UPDATE_NOTEPAD_FAIL: 'UPDATE_NOTEPAD_FAIL',

  REMOVE_NOTEPAD: 'REMOVE_NOTEPAD',
  REMOVE_NOTEPAD_SUCCESS: 'REMOVE_NOTEPAD_SUCCESS',
  REMOVE_NOTEPAD_FAIL: 'REMOVE_NOTEPAD_FAIL',

  FETCH_NOTEPAD_LIST: 'FETCH_NOTEPAD_LIST',
  FETCH_NOTEPAD_LIST_SUCCESS: 'FETCH_NOTEPAD_LIST_SUCCESS',
  FETCH_NOTEPAD_LIST_FAIL: 'FETCH_NOTEPAD_LIST_FAIL',
}
